/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Assignment;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author USER
 */
public class DepartmentFrame extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(DepartmentFrame.class.getName());

    private void loadTableData(){
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) deptTable.getModel();
        model.setRowCount(0);
        
        DepartmentFileHandle handle = new DepartmentFileHandle();
        String[][] allDepts = handle.getAllDepartments();
        
        for (int i = 0; i < allDepts.length; i++){
            if (allDepts[i][0] != null){
                model.addRow(allDepts[i]);
            }
        }
        
        deptTable.getColumnModel().getColumn(0).setPreferredWidth(100);  
        deptTable.getColumnModel().getColumn(1).setPreferredWidth(120); 
        deptTable.getColumnModel().getColumn(2).setPreferredWidth(300); 
    }
    /**
     * Creates new form DepartmentFrame
     */
    public DepartmentFrame() {
        initComponents();
        loadTableData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtDeptID = new javax.swing.JTextField();
        txtDeptName = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        txtDeptDesc = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        deptTable = new javax.swing.JTable();
        btnUpdate = new javax.swing.JButton();
        btnClear = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Department ID");

        jLabel2.setText("Department Name");

        txtDeptID.addActionListener(this::txtDeptIDActionPerformed);

        btnAdd.setText("Add New");
        btnAdd.addActionListener(this::btnAddActionPerformed);

        jLabel3.setText("Desciption");

        deptTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Department ID", "Name", "Description"
            }
        ));
        deptTable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                deptTableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(deptTable);
        if (deptTable.getColumnModel().getColumnCount() > 0) {
            deptTable.getColumnModel().getColumn(0).setResizable(false);
            deptTable.getColumnModel().getColumn(1).setResizable(false);
            deptTable.getColumnModel().getColumn(2).setResizable(false);
        }

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(this::btnUpdateActionPerformed);

        btnClear.setText("Clear");
        btnClear.addActionListener(this::btnClearActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(71, 71, 71)
                                .addComponent(btnAdd)
                                .addGap(72, 72, 72)
                                .addComponent(btnUpdate)
                                .addGap(79, 79, 79)
                                .addComponent(btnClear)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtDeptDesc, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeptName, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtDeptID, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(66, 66, 66)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 517, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(49, 49, 49))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel1)
                    .addComponent(txtDeptID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtDeptName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(txtDeptDesc, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(63, 63, 63)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnAdd)
                    .addComponent(btnUpdate)
                    .addComponent(btnClear))
                .addContainerGap(197, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {                                       
        // TODO add your handling code here:
        String id = txtDeptID.getText();
        String name = txtDeptName.getText();
        String desc = txtDeptDesc.getText();
        
        if (id.isEmpty() || name.isEmpty()){
            javax.swing.JOptionPane.showMessageDialog(this, "ID and Name cannot be empty.");
            return;
        }
        
        DepartmentFileHandle handle = new DepartmentFileHandle();
        if (handle.addDepartment(id, name, desc)){
            javax.swing.JOptionPane.showMessageDialog(this, "Added Successfully.");
            loadTableData();
        } else{
            javax.swing.JOptionPane.showMessageDialog(this, "Error Adding Department.");
        }
    }                                      

    private void txtDeptIDActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
    }                                         

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
        String id = txtDeptID.getText();
        String name = txtDeptName.getText();
        String desc = txtDeptDesc.getText();
        
        DepartmentFileHandle handle = new DepartmentFileHandle();
        if (handle.updateDepartment(id, name, desc)){
            javax.swing.JOptionPane.showMessageDialog(this, "Updated Successfully.");
            loadTableData();
        } else{
            javax.swing.JOptionPane.showMessageDialog(this, "Error Updating Department.");
        }
    }                                         

    private void btnClearActionPerformed(java.awt.event.ActionEvent evt) {                                         
        // TODO add your handling code here:
        txtDeptID.setText("");
        txtDeptName.setText("");
        txtDeptDesc.setText("");
        txtDeptID.setEditable(true);
    }                                        

    private void deptTableMouseClicked(java.awt.event.MouseEvent evt) {                                       
        // TODO add your handling code here:
        DefaultTableModel model = (DefaultTableModel) deptTable.getModel();
        int selectedRow = deptTable.getSelectedRow();
        
        txtDeptID.setText(model.getValueAt(selectedRow, 0).toString());
        txtDeptName.setText(model.getValueAt(selectedRow, 1).toString());
        txtDeptDesc.setText(model.getValueAt(selectedRow, 2).toString());
        
        txtDeptID.setEditable(false);
    }                                      

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new DepartmentFrame().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClear;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JTable deptTable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField txtDeptDesc;
    private javax.swing.JTextField txtDeptID;
    private javax.swing.JTextField txtDeptName;
    // End of variables declaration                   
}
